[package]
name = "bench"
version = "0.1.0"
authors = ["Fabian Beckmann <fb@phaseq.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = ">= 0.20.0", features=["bundled"] }
rocket = "*"
rocket_contrib = { version = "*", features=["tera_templates"] }
tera = "*"
serde = "*"
serde_derive = "*"